// ─── CATEGORY DEFINITIONS ────────────────────────────────────────
const CATEGORIES = {
  body:    { label: 'Body',    color: '#e07b6a', why: 'Body-part vocabulary is among the most universally documented — fieldworkers always asked for these first.' },
  nature:  { label: 'Nature',  color: '#6db87a', why: 'Words for the natural world were central to daily life and often among the first recorded.' },
  kinship: { label: 'Kinship', color: '#7ba8d4', why: 'Kinship terms reveal how a culture organized society. Linguists prioritized these early.' },
  numbers: { label: 'Numbers', color: '#c89ae0', why: 'Counting systems were among the first things documented — often revealing base-12 or base-5 structures foreign to English.' },
  time:    { label: 'Time',    color: '#d4b86a', why: 'Time words survived because fieldworkers needed to ask about seasons, cycles, and daily patterns.' },
  action:  { label: 'Action',  color: '#e0a06a', why: 'Core verbs — eat, sleep, walk, speak — were documented universally in early wordlists.' },
  emotion: { label: 'Emotion', color: '#e06a9a', why: 'Emotion words were rarely documented early. When they survive, it is often by accident.' },
  place:   { label: 'Place',   color: '#6ac8c8', why: 'Place-words survived tied to geography — rivers, forests, hills that still exist on maps.' },
  spirit:  { label: 'Spirit',  color: '#a0a0e0', why: 'Ceremonial and spiritual language was often the last to be shared with outsiders — what survives is rarely complete.' },
  food:    { label: 'Food',    color: '#b8d46d', why: 'Food words were documented because linguists and traders needed them. Often the most culturally specific.' },
  other:   { label: 'Other',   color: '#8a8a8a', why: 'These words survived by chance — noted in margins, recalled by a grandchild, found in a missionary\'s diary.' },
};

// ─── LANGUAGE DATA ────────────────────────────────────────────────
const LANGUAGES = {

  chamicuro: {
    name: 'Chamicuro',
    region: 'Amazonian Peru',
    status: 'Critically endangered',
    statusNote: 'Fewer than 10 elderly speakers remain',
    estimated: 40000,
    documented: 600,
    words: [
      { native: 'napola',       pronunciation: 'na-PO-la',        english: 'water / river',    category: 'nature',  note: 'The word for water and river is the same — the river was not seen as a thing separate from water itself.', },
      { native: 'shikopilawaka',pronunciation: 'shi-ko-pi-LA-wa-ka', english: 'the world',    category: 'place',   note: 'Literally "the place where we are." The world was defined as the inhabited place, not the earth as a globe.', },
      { native: 'yawala',       pronunciation: 'ya-WA-la',        english: 'moon',             category: 'nature',  note: 'The moon governed planting and fishing cycles. Chamicuro had multiple words for moon phases; only this root survives.', },
      { native: 'pachisi',      pronunciation: 'pa-CHI-si',       english: 'fire',             category: 'nature',  note: 'One of the oldest roots in the Maipuran language family — nearly identical across related Amazonian languages.', },
      { native: 'anala',        pronunciation: 'a-NA-la',         english: 'my mother',        category: 'kinship', note: 'The possessive prefix is built into the word — you cannot say "mother" without claiming her as yours.', },
      { native: 'tataki',       pronunciation: 'ta-TA-ki',        english: 'my father',        category: 'kinship', note: 'A near-universal Amazonian root for father, suggesting deep common ancestry among the basin\'s languages.', },
      { native: 'machi',        pronunciation: 'MA-chi',          english: 'hand',             category: 'body',    note: 'Also meant "five" — the counting system was based on fingers, making hand and the number five the same word.', },
      { native: 'kana',         pronunciation: 'KA-na',           english: 'eye',              category: 'body',    note: 'Eye and the verb "to see" shared the same root. Perception and the organ were not separated linguistically.', },
      { native: 'wayra',        pronunciation: 'WAY-ra',          english: 'wind',             category: 'nature',  note: 'Borrowed from Quechua during the Incan expansion — a linguistic scar of colonization visible in the vocabulary.', },
      { native: 'amani',        pronunciation: 'a-MA-ni',         english: 'fish',             category: 'food',    note: 'The most important protein source of the Amazon. Chamicuro had at least 30 words for specific fish species; only the generic root survives.', },
      { native: 'yoka',         pronunciation: 'YO-ka',           english: 'one',              category: 'numbers', note: 'The number system was decimal but counting above ten required compound phrases, none of which are fully documented.', },
      { native: 'polka',        pronunciation: 'POL-ka',          english: 'two',              category: 'numbers', note: '', },
      { native: 'mishki',       pronunciation: 'MISH-ki',         english: 'sweet / delicious',category: 'food',    note: 'Sweet taste was culturally important — associated with fruit, honey, and also with kind words.', },
      { native: 'shawa',        pronunciation: 'SHA-wa',          english: 'forest / jungle',  category: 'place',   note: 'The forest was not wilderness — it was home. This word had no negative connotation, unlike its Spanish equivalent.', },
      { native: 'kamari',       pronunciation: 'ka-MA-ri',        english: 'spirit / demon',   category: 'spirit',  note: 'Missionaries documented this word because they feared it. Its full spiritual meaning — which was not simply "evil" — is lost.', },
      { native: 'tawa',         pronunciation: 'TA-wa',           english: 'four',             category: 'numbers', note: '', },
      { native: 'punchaw',      pronunciation: 'PUN-chaw',        english: 'day / sun',        category: 'time',    note: 'Day and sun were the same word. Time was measured by light, not by hours.', },
      { native: 'tutayay',      pronunciation: 'tu-ta-YAY',       english: 'to become night',  category: 'time',    note: 'Night was not a noun but a verb — darkness was something that happened, not a state that existed.', },
      { native: 'mikuy',        pronunciation: 'MI-kuy',          english: 'to eat',           category: 'action',  note: 'The root verb for eating. Eating together had social and ritual significance — there were separate words for eating alone.', },
      { native: 'rimay',        pronunciation: 'ri-MAY',          english: 'to speak',         category: 'action',  note: 'Also meant "to exist socially." A person who could not speak was considered outside the community in a profound way.', },
      { native: 'wañuy',        pronunciation: 'wa-ÑUIY',         english: 'to die',           category: 'action',  note: 'Death was framed as a journey rather than an ending. The verb\'s grammatical form implied continuation.', },
      { native: 'llaki',        pronunciation: 'YA-ki',           english: 'sadness / grief',  category: 'emotion', note: 'One of the few emotion words preserved. It covers grief, longing, and the specific sadness of separation.', },
      { native: 'kushiy',       pronunciation: 'KU-shiy',         english: 'joy / happiness',  category: 'emotion', note: 'Documented by a Spanish missionary who noted it was the word most frequently used in song.', },
      { native: 'unu',          pronunciation: 'U-nu',            english: 'deep water',       category: 'nature',  note: 'Different from napola — this specifically meant dangerous, deep, or sacred water. Rivers had personalities.', },
      { native: 'puka',         pronunciation: 'PU-ka',           english: 'red',              category: 'other',   note: 'Color words in Chamicuro were tied to natural objects — red was the color of a specific Amazonian berry.', },
      { native: 'yuraq',        pronunciation: 'YU-raq',          english: 'white',            category: 'other',   note: 'White was associated with bones, death, and the spirit world — not with purity as in European traditions.', },
      { native: 'inti',         pronunciation: 'IN-ti',           english: 'sun',              category: 'nature',  note: 'Shared with Quechua — the sun deity name spread through cultural contact across the entire Andean region.', },
      { native: 'rumi',         pronunciation: 'RU-mi',           english: 'stone / rock',     category: 'nature',  note: 'Stones were considered ancient beings with memory. Certain rocks had names and were greeted.', },
      { native: 'chaki',        pronunciation: 'CHA-ki',          english: 'foot / path',      category: 'body',    note: 'Foot and path were the same word — a path was defined as the place where feet have been.', },
      { native: 'sami',         pronunciation: 'SA-mi',           english: 'luck / fate / grace', category: 'spirit', note: 'An untranslatable concept covering good fortune, divine grace, and inherent life force. No single English word captures it.', },
    ]
  },

  yuchi: {
    name: 'Yuchi',
    region: 'Oklahoma, USA',
    status: 'Critically endangered',
    statusNote: 'Fewer than 5 fluent speakers remain — a language isolate with no known relatives',
    estimated: 50000,
    documented: 400,
    words: [
      { native: 'Tsoyaha',   pronunciation: 'TSO-ya-ha',    english: 'children of the sun / us', category: 'kinship', note: 'The Yuchi name for themselves. The word contains the sun and the concept of descent — identity was inseparable from origin.', },
      { native: 'shono',     pronunciation: 'SHO-no',       english: 'water',                   category: 'nature',  note: 'Yuchi water-words differed by motion — still water, flowing water, and sacred water were distinct concepts.', },
      { native: 'dâ',        pronunciation: 'dah',          english: 'sun',                     category: 'nature',  note: 'The sun was the source of Yuchi identity. "Tsoyaha" literally contains this root.', },
      { native: 'sho\'ne',   pronunciation: 'SHOH-neh',     english: 'fire',                    category: 'nature',  note: 'Fire was kept continuously in the ceremonial square ground — extinguishing it was a grave act.', },
      { native: 'fa',        pronunciation: 'fah',          english: 'I (if I am Yuchi)',        category: 'other',   note: 'Uniquely, Yuchi has different words for "I" depending on whether you are Yuchi or not. This is found in almost no other language on earth.', },
      { native: 'swa',       pronunciation: 'swah',         english: 'I (if I am not Yuchi)',    category: 'other',   note: 'The non-Yuchi first person. Identity was so central that grammar itself encoded whether you were inside or outside the community.', },
      { native: 'gote',      pronunciation: 'GO-teh',       english: 'man / person',             category: 'kinship', note: 'The word for man and person were the same. Gender was not the primary category — humanity was.', },
      { native: 'yale',      pronunciation: 'YA-leh',       english: 'woman',                   category: 'kinship', note: '', },
      { native: 'hâ',        pronunciation: 'hah',          english: 'earth / ground',           category: 'place',   note: 'The earth was a living being. The word was also used in ceremony when addressing the land directly.', },
      { native: 'wethâ',     pronunciation: 'WEH-thah',     english: 'sky / above',              category: 'place',   note: 'Sky was a place one could go, not merely an overhead expanse. The afterlife was directionally above.', },
      { native: 'sâle',      pronunciation: 'SAH-leh',      english: 'deer',                    category: 'nature',  note: 'Deer was the most important game animal and appears in ceremony, story, and prayer. Dozens of deer-related words are undocumented.', },
      { native: 'dâgone',    pronunciation: 'DAH-go-neh',   english: 'Green Corn ceremony',      category: 'spirit',  note: 'The most sacred annual event. The word cannot be fully translated — it encompasses renewal, gratitude, and the entire ceremonial cycle.', },
      { native: 'nâ',        pronunciation: 'nah',          english: 'one',                     category: 'numbers', note: 'The Yuchi number system is vigesimal (base 20) — counting was done in twenties, not tens.', },
      { native: 'le',        pronunciation: 'leh',          english: 'two',                     category: 'numbers', note: '', },
      { native: 'sâgone',    pronunciation: 'SAH-go-neh',   english: 'three',                   category: 'numbers', note: '', },
      { native: 'â\'ne',     pronunciation: 'AH-neh',       english: 'four',                    category: 'numbers', note: '', },
      { native: 'shâhe',     pronunciation: 'SHAH-heh',     english: 'five',                    category: 'numbers', note: 'Five — the hand count. Above five, Yuchi numbers became compound phrases.', },
      { native: 'yâ\'ne',    pronunciation: 'YAH-neh',      english: 'to speak / to say',       category: 'action',  note: 'Speaking was considered a creative act — words had power to make things real.', },
      { native: 'kwâ',       pronunciation: 'kwah',         english: 'to eat',                  category: 'action',  note: '', },
      { native: 'wâ',        pronunciation: 'wah',          english: 'to go',                   category: 'action',  note: 'Motion verbs in Yuchi specified direction relative to the river — going upstream and downstream were different words.', },
      { native: 'tsoya',     pronunciation: 'TSO-ya',       english: 'sun-descended / sacred',   category: 'spirit',  note: 'The root that gives the Yuchi their name. Its full spiritual sense — divine origin, sacred duty — cannot be rendered in English.', },
      { native: 'shone\'ne', pronunciation: 'SHOH-neh-neh', english: 'longhouse',               category: 'place',   note: 'The communal structure where ceremony happened. Its name contained the word for fire — the building was defined by what burned inside it.', },
      { native: 'gâ',        pronunciation: 'gah',          english: 'tree',                    category: 'nature',  note: 'A generic term. Yuchi had specific names for dozens of tree species, most undocumented.', },
      { native: 'wele',      pronunciation: 'WEH-leh',      english: 'bird',                    category: 'nature',  note: 'Birds were messengers between the human and spirit world. The word for bird and the word for spirit-message were related.', },
      { native: 'tsâ',       pronunciation: 'tsah',         english: 'night / darkness',         category: 'time',    note: 'Night was a time of spirits, not merely of darkness. Certain words could only be spoken at night.', },
      { native: 'dâle',      pronunciation: 'DAH-leh',      english: 'day / sunlight',           category: 'time',    note: 'Day was defined by sunlight, not by clock hours. A cloudy day was linguistically ambiguous.', },
      { native: 'hone',      pronunciation: 'HO-neh',       english: 'old / ancestor',           category: 'kinship', note: 'Old age and ancestry were one concept — to be old was to be closer to the ancestors.', },
      { native: 'shâwone',   pronunciation: 'SHAH-wo-neh',  english: 'longing / homesickness',   category: 'emotion', note: 'One of few documented emotion words. After the forced relocation to Oklahoma, this word\'s use increased dramatically, according to field notes.', },
      { native: 'gâwâ',      pronunciation: 'GAH-wah',      english: 'hand',                    category: 'body',    note: '', },
      { native: 'wone',      pronunciation: 'WO-neh',       english: 'heart',                   category: 'body',    note: 'Heart was the seat of thought, not feeling — in Yuchi, the heart was where decisions were made.', },
    ]
  },

  manx: {
    name: 'Manx',
    region: 'Isle of Man',
    status: 'Revitalizing',
    statusNote: 'Last native speaker died 1974 — a few hundred second-language speakers now exist',
    estimated: 35000,
    documented: 8000,
    words: [
      { native: 'Moghrey mie',  pronunciation: 'MO-ree my',       english: 'good morning',     category: 'action',  note: 'The most-used greeting. It survives because it was recorded on audio by BBC linguists in the 1950s, listening to Ned Maddrell, the last native speaker.', },
      { native: 'Fastyr mie',   pronunciation: 'FAS-tir my',      english: 'good afternoon',   category: 'action',  note: '', },
      { native: 'Oie vie',      pronunciation: 'ee VY',            english: 'good night',       category: 'action',  note: '', },
      { native: 'Gura mie ayd', pronunciation: 'GU-ra my eyd',    english: 'thank you',        category: 'action',  note: 'Literally "may good be with you." Gratitude was framed as a wish, not a receipt.', },
      { native: 'mooir',        pronunciation: 'MOOIR',            english: 'sea',              category: 'nature',  note: 'On an island 32 miles long, the sea was everything — livelihood, boundary, and myth. Manx had dozens of sea-words; most survive.', },
      { native: 'ellan',        pronunciation: 'EL-an',            english: 'island',           category: 'place',   note: 'The Isle of Man\'s Manx name — Ellan Vannin — contains this word. Island was identity.', },
      { native: 'awin',         pronunciation: 'AW-in',            english: 'river',            category: 'nature',  note: '', },
      { native: 'geay',         pronunciation: 'gay',              english: 'wind',             category: 'nature',  note: 'Wind was named by direction — east wind, west wind, storm wind were different words. Only the generic root survives in common use.', },
      { native: 'sniaghtey',    pronunciation: 'SNYAKH-tee',       english: 'snow',             category: 'nature',  note: 'Rarely needed on the mild Isle of Man, but the word survived in proverbs about hard times.', },
      { native: 'blein',        pronunciation: 'blayn',            english: 'year',             category: 'time',    note: 'Manx had a rich calendar of seasonal festivals. The year was not a number but a cycle of events.', },
      { native: 'oie',          pronunciation: 'ee',               english: 'night',            category: 'time',    note: 'Celtic languages often counted by nights, not days — "a fortnight" preserves this in English.', },
      { native: 'laa',          pronunciation: 'laa',              english: 'day',              category: 'time',    note: '', },
      { native: 'ayr',          pronunciation: 'air',              english: 'father',           category: 'kinship', note: '', },
      { native: 'moir',         pronunciation: 'moir',             english: 'mother',           category: 'kinship', note: '', },
      { native: 'mac',          pronunciation: 'mak',              english: 'son',              category: 'kinship', note: 'This root survives in thousands of Manx and Scottish surnames beginning with Mac/Mc.', },
      { native: 'inneen',       pronunciation: 'IN-een',           english: 'daughter / girl',  category: 'kinship', note: '', },
      { native: 'dooinney',     pronunciation: 'DUN-ye',           english: 'man / person',     category: 'kinship', note: '', },
      { native: 'ben',          pronunciation: 'ben',              english: 'woman / wife',     category: 'kinship', note: 'Also meant "wife" — the dual meaning reflects old social structure where woman and wife were the same role in language.', },
      { native: 'thie',         pronunciation: 'tie',              english: 'house / home',     category: 'place',   note: 'Home on a small island meant something specific — near the sea, exposed to weather. The word carried those sensations.', },
      { native: 'buigh',        pronunciation: 'bwee',             english: 'yellow',           category: 'other',   note: 'Yellow was the color of gorse — a plant that blooms year-round on the Isle of Man, a constant in the landscape.', },
      { native: 'jiarg',        pronunciation: 'jarg',             english: 'red',              category: 'other',   note: '', },
      { native: 'glass',        pronunciation: 'glas',             english: 'green / blue-grey',category: 'other',   note: 'Manx "glass" covers the colour range of sea, sky, and grass — English needs three separate words for this.', },
      { native: 'yn pishyr',    pronunciation: 'un PISH-ir',       english: 'the magpie / omen-bird', category: 'spirit', note: 'The magpie was a creature of prophecy. Meeting one alone was bad luck; alone or in pairs had specific ritual meanings.', },
      { native: 'ny ferrishyn', pronunciation: 'nuh FER-i-sheen',  english: 'the fairies',      category: 'spirit',  note: 'The Manx fairy-faith was rich and specific. Fairies were not small — they were parallel beings who could take and give.', },
      { native: 'cree',         pronunciation: 'kree',             english: 'heart',            category: 'body',    note: 'Heart was the center of courage and love both — a courageous person "had heart."', },
      { native: 'laue',         pronunciation: 'lau',              english: 'hand',             category: 'body',    note: '', },
      { native: 'sooill',       pronunciation: 'sul',              english: 'eye',              category: 'body',    note: '', },
      { native: 'beeal',        pronunciation: 'beel',             english: 'mouth',            category: 'body',    note: 'Mouth was also "opening" — a cave, a harbor entrance, a gap in the hills. Anatomy and landscape shared a vocabulary.', },
      { native: 'arrane',       pronunciation: 'AR-an',            english: 'song',             category: 'action',  note: 'Song was central to Manx culture. Ned Maddrell, the last speaker, was recorded primarily through songs.', },
      { native: 'treih',        pronunciation: 'tray',             english: 'sad / wretched',   category: 'emotion', note: 'Documented frequently in old poems about the island\'s decline. The word carries loss specifically, not just sadness.', },
    ]
  },

  akkadian: {
    name: 'Akkadian',
    region: 'Ancient Mesopotamia',
    status: 'Extinct',
    statusNote: 'Last written records ~100 CE — once the lingua franca of the ancient world',
    estimated: 60000,
    documented: 25000,
    words: [
      { native: 'šulmu',     pronunciation: 'SHUL-mu',     english: 'peace / health / greeting', category: 'action',  note: 'The standard greeting. The root šlm appears across Semitic languages — in Arabic "salaam," Hebrew "shalom." Peace was the original hello.', },
      { native: 'šarru',     pronunciation: 'SHAR-ru',     english: 'king',                     category: 'kinship', note: 'One of the most common words in cuneiform — every royal inscription began with the king\'s name and titles.', },
      { native: 'mātu',      pronunciation: 'MAA-tu',      english: 'land / country',            category: 'place',   note: 'Every Mesopotamian king claimed to be "king of the four lands." Mātu was the known world, bounded by mountains and sea.', },
      { native: 'mû',        pronunciation: 'moo',         english: 'water',                    category: 'nature',  note: 'Water — specifically the controlled, canal-fed water of Mesopotamia. The irrigation system made civilization possible and the word was sacred.', },
      { native: 'šamû',      pronunciation: 'SHA-moo',     english: 'sky / heaven / rain',       category: 'nature',  note: 'Sky, heaven, and rain were the same word. Rain fell from the gods — the celestial and the meteorological were one.', },
      { native: 'ilu',       pronunciation: 'i-LU',        english: 'god',                      category: 'spirit',  note: 'The Mesopotamian pantheon had thousands of gods. Ilu was the generic term — deity itself. It became "El" in Hebrew, "Allah" in Arabic.', },
      { native: 'eṭlu',      pronunciation: 'ET-lu',       english: 'young man / hero',          category: 'kinship', note: 'The word used for Gilgamesh — the hero. Heroism and youth were the same concept.', },
      { native: 'sinništu',  pronunciation: 'SIN-nish-tu', english: 'woman',                    category: 'kinship', note: '', },
      { native: 'napištu',   pronunciation: 'na-PISH-tu',  english: 'life / soul / breath',      category: 'spirit',  note: 'Life was breath. The soul was what made air move through the body. When Gilgamesh seeks immortality, he seeks to preserve his napištu.', },
      { native: 'mītu',      pronunciation: 'MEE-tu',      english: 'dead person / the dead',    category: 'spirit',  note: 'Death was a category of being, not an absence. The dead existed in the Underworld — a mirror of the living world.', },
      { native: 'qaqqadu',   pronunciation: 'qaq-QA-du',   english: 'head',                     category: 'body',    note: '', },
      { native: 'īnu',       pronunciation: 'EE-nu',       english: 'eye',                      category: 'body',    note: 'Eyes were considered windows to divine truth — witnesses in legal proceedings swore "before the eye of the god."', },
      { native: 'libbu',     pronunciation: 'LIB-bu',      english: 'heart / inner self',        category: 'body',    note: 'The heart was the seat of thought and identity in Akkadian — the equivalent of the modern "self." "In his heart he knew..." was a legal phrase.', },
      { native: 'qātu',      pronunciation: 'QAA-tu',      english: 'hand',                     category: 'body',    note: 'Hand also meant "power" and "control." To be "in someone\'s hand" was to be under their authority.', },
      { native: 'šatû',      pronunciation: 'SHA-tu',      english: 'to drink',                  category: 'action',  note: 'Drinking was ritually significant — shared drinking sealed contracts and alliances in Mesopotamian culture.', },
      { native: 'akālu',     pronunciation: 'a-KAA-lu',    english: 'to eat',                    category: 'action',  note: '', },
      { native: 'alāku',     pronunciation: 'a-LAA-ku',    english: 'to go / to walk',           category: 'action',  note: 'One of the most conjugated verbs in cuneiform — its many forms tell us that going was as important a concept as being.', },
      { native: 'qabû',      pronunciation: 'qa-BUU',      english: 'to say / to decree',        category: 'action',  note: 'Saying was decreeing — when a king or god spoke, reality changed. Language was law.', },
      { native: 'išten',     pronunciation: 'ISH-ten',     english: 'one',                      category: 'numbers', note: 'Akkadian used a sexagesimal (base 60) number system — why we still have 60 seconds and 360 degrees.', },
      { native: 'šina',      pronunciation: 'SHI-na',      english: 'two',                      category: 'numbers', note: '', },
      { native: 'šalāšu',    pronunciation: 'sha-LAA-shu', english: 'three',                    category: 'numbers', note: '', },
      { native: 'erbe',      pronunciation: 'ER-be',       english: 'four',                     category: 'numbers', note: '', },
      { native: 'ūmu',       pronunciation: 'UU-mu',       english: 'day / storm',              category: 'time',    note: 'Day and storm were the same word — because the Mesopotamian day was defined by whether the sun was visible.', },
      { native: 'šattu',     pronunciation: 'SHAT-tu',     english: 'year',                     category: 'time',    note: 'The year was defined by the flooding of the rivers — agriculture, not astronomy, was the primary time-keeper.', },
      { native: 'kalbu',     pronunciation: 'KAL-bu',      english: 'dog',                      category: 'nature',  note: 'Dogs were sacred to certain healing goddesses — temple dogs licked the wounds of the sick as a form of treatment.', },
      { native: 'nāru',      pronunciation: 'NAA-ru',      english: 'river / stream',            category: 'nature',  note: 'The Tigris and Euphrates were the axes of civilization. River-words appear more frequently in cuneiform than almost any other category.', },
      { native: 'kīma',      pronunciation: 'KEE-ma',      english: 'like / as / when',          category: 'other',   note: 'The most common comparison word in Akkadian poetry — the Epic of Gilgamesh begins with this word.', },
      { native: 'tukultu',   pronunciation: 'tu-KUL-tu',   english: 'trust / reliance',          category: 'emotion', note: 'An untranslatable concept: the feeling of leaning on someone who will not fall. Appears in prayers and love letters both.', },
      { native: 'aḫāzu',     pronunciation: 'a-HAA-zu',    english: 'to seize / to marry',       category: 'action',  note: 'To marry was to seize — the same verb. A discomforting linguistic window into ancient power dynamics.', },
      { native: 'ašru',      pronunciation: 'ASH-ru',      english: 'place / sacred site',       category: 'place',   note: 'Place was not neutral — all named places had a character and often a deity. Geography was theology.', },
    ]
  },

  muscogee: {
    name: 'Muscogee',
    region: 'Oklahoma & Florida, USA',
    status: 'Endangered',
    statusNote: '~5,000 speakers, mostly elderly — revitalization underway',
    estimated: 45000,
    documented: 3000,
    words: [
      { native: 'Hesci',     pronunciation: 'HIS-chee',     english: 'hello',                   category: 'action',  note: 'The standard greeting, now widely known through revitalization efforts. One of the first words taught to new learners.', },
      { native: 'Mvto',      pronunciation: 'MAH-do',        english: 'thank you',               category: 'action',  note: 'The spelling looks nothing like the pronunciation — Muscogee orthography was developed by outsiders and never perfectly matched the sounds.', },
      { native: 'Este',      pronunciation: 'IS-tee',        english: 'person / human being',    category: 'kinship', note: 'The Muscogee people\'s name for themselves. To be a person was to be Muscogee — community defined humanity.', },
      { native: 'Ekvnv',     pronunciation: 'i-GUH-nuh',    english: 'earth / ground',           category: 'place',   note: 'Earth was alive. The ground held the bones of ancestors — to be moved from one place was to be separated from the dead.', },
      { native: 'Owv',       pronunciation: 'OH-wuh',        english: 'water',                   category: 'nature',  note: 'Water was ceremonially central — Green Corn ceremony included ritual bathing in running water.', },
      { native: 'Hvse',      pronunciation: 'HUH-see',       english: 'sun / time',              category: 'time',    note: 'Sun and time were the same word. Before clocks, time was the position of the sun.', },
      { native: 'Niha',      pronunciation: 'NEE-ha',        english: 'moon',                    category: 'time',    note: 'Months were named by the moon — planting moon, harvest moon, cold moon. Only the generic word survives.', },
      { native: 'Eco',       pronunciation: 'IT-cho',        english: 'deer',                    category: 'nature',  note: 'The deer was the most important game animal and a figure in ceremony. Its bones were used in healing rituals.', },
      { native: 'Fvtcv',     pronunciation: 'FUH-chuh',      english: 'bird',                    category: 'nature',  note: 'Birds were messengers. Certain birds appearing at certain times carried specific meanings.', },
      { native: 'Cetto',     pronunciation: 'CHIT-toh',      english: 'snake',                   category: 'nature',  note: 'The horned serpent was a powerful spiritual being — not the same as an ordinary snake, but the word was the same.', },
      { native: 'Nettv',     pronunciation: 'NIT-tuh',       english: 'day',                     category: 'time',    note: '', },
      { native: 'Niche',     pronunciation: 'NEE-chee',      english: 'night',                   category: 'time',    note: 'Night was the time for stories — certain oral literature could only be told after dark.', },
      { native: 'Rakko',     pronunciation: 'RAHK-koh',      english: 'big / great',             category: 'other',   note: 'Greatness was physical scale — a great chief was literally a big person. Abstract status was expressed through size.', },
      { native: 'Heckv',     pronunciation: 'HIK-kuh',       english: 'to see / to know',        category: 'action',  note: 'Seeing and knowing were the same verb. Knowledge came through direct witness — you knew what you had seen.', },
      { native: 'Poyetv',    pronunciation: 'POH-yit-uh',    english: 'to speak',                category: 'action',  note: 'Speaking was gendered — there were subtle grammatical differences when men spoke versus when women spoke. These distinctions are nearly lost.', },
      { native: 'Liketv',    pronunciation: 'LIK-it-uh',     english: 'to sit',                  category: 'action',  note: 'Sitting was the position of authority — the chief sat while others stood. The verb carried political weight.', },
      { native: 'Yvhiketv',  pronunciation: 'yuh-HEE-kit-uh',english: 'to sing',                category: 'action',  note: 'Song was inseparable from ceremony. The Green Corn songs had specific sequences that could not be altered.', },
      { native: 'Cvpko',     pronunciation: 'CHUP-koh',      english: 'heart',                   category: 'body',    note: 'Heart was courage. A coward "had a small heart" — size metaphors pervaded emotional vocabulary.', },
      { native: 'Nvcke',     pronunciation: 'NUH-chkee',     english: 'eye',                     category: 'body',    note: '', },
      { native: 'Pv\'kpv',   pronunciation: 'PUH-kpuh',      english: 'hand',                    category: 'body',    note: '', },
      { native: 'Nakv',      pronunciation: 'NA-kuh',         english: 'nose',                    category: 'body',    note: '', },
      { native: 'Cvto',      pronunciation: 'CHUH-toh',      english: 'stone / rock',             category: 'nature',  note: 'Certain stones were considered spiritually alive and were carried as medicine.', },
      { native: 'Vhvlwv',    pronunciation: 'uh-HUHL-wuh',   english: 'smoke',                   category: 'nature',  note: 'Smoke carried prayers upward. Tobacco smoke was how humans communicated with the spirit world.', },
      { native: 'Huttvlke',  pronunciation: 'hut-TUHL-kee',  english: 'Green Corn ceremony',     category: 'spirit',  note: 'The most sacred annual event — a time of renewal, forgiveness, and the lighting of new fire. The word cannot be translated without losing its meaning.', },
      { native: 'Ibofanga',  pronunciation: 'i-bo-FAHN-ga',  english: 'love',                    category: 'emotion', note: 'Love was a relational verb, not a noun. It described an ongoing action between specific people — not a state of being.', },
      { native: 'Enokkov',   pronunciation: 'i-NOK-koh',     english: 'brave / courageous',      category: 'emotion', note: 'Documented frequently in accounts of war and ceremony. Courage was a virtue named and praised in public.', },
      { native: 'Hiyayetv',  pronunciation: 'hi-YAY-it-uh',  english: 'to be sad / to mourn',   category: 'emotion', note: 'Grief was expressed publicly — mourning had a ceremonial form and duration. Private grief was culturally unusual.', },
      { native: 'Totkv',     pronunciation: 'TOHT-kuh',      english: 'fire',                    category: 'spirit',  note: 'Sacred fire was kept burning continuously. When the Muscogee were forcibly removed on the Trail of Tears, they carried coals.', },
      { native: 'Cvmpv',     pronunciation: 'CHUM-puh',      english: 'good / beautiful',        category: 'other',   note: 'Good and beautiful were the same word. Ethics and aesthetics were not separated — a good act was literally a beautiful one.', },
      { native: 'Kerretv',   pronunciation: 'KIR-it-uh',     english: 'to remember',             category: 'action',  note: 'Memory was active, not passive — remembering was something you did deliberately, with effort and intention.', },
    ]
  },

  coptic: {
    name: 'Coptic',
    region: 'Egypt',
    status: 'Extinct (liturgical)',
    statusNote: 'Last spoken ~17th century CE — still used in Coptic Church liturgy',
    estimated: 55000,
    documented: 20000,
    words: [
      { native: 'ⲛⲟⲩⲧⲉ',     pronunciation: 'NU-teh',        english: 'God',                    category: 'spirit',  note: 'The Coptic word for God — descended directly from ancient Egyptian "nṯr." Three thousand years of the divine, in one small word.', },
      { native: 'ⲙⲟⲟⲩ',       pronunciation: 'MOOU',          english: 'water',                  category: 'nature',  note: 'Descended from ancient Egyptian "mw." Water — the Nile — was the source of all Egyptian life and religion.', },
      { native: 'ⲣⲁⲛ',         pronunciation: 'ran',           english: 'name',                   category: 'other',   note: 'Your name was your identity and your power. To know someone\'s true name was to have power over them — a belief spanning 3,000 years of Egyptian religion.', },
      { native: 'ⲛⲓⲫⲏⲧ',       pronunciation: 'ni-FEET',       english: 'the heavens',            category: 'place',   note: 'Heaven was plural and layered — different heavens for different divine beings.', },
      { native: 'ⲡⲕⲁϩ',        pronunciation: 'p-KAH',         english: 'the earth',              category: 'place',   note: 'Earth was gendered and alive. "Ka" was the life force — the earth\'s name contained it.', },
      { native: 'ⲣⲏ',          pronunciation: 'RAY',           english: 'sun / the sun god',      category: 'spirit',  note: 'The sun god\'s name became the word for the sun. Three thousand years of solar worship compressed into two letters.', },
      { native: 'ⲛⲟⲩⲃ',        pronunciation: 'noob',          english: 'gold',                   category: 'other',   note: 'Gold was the flesh of the gods. The word survived because gold itself survived — in jewelry, in churches, in the desert.', },
      { native: 'ⲁϩⲟⲙ',        pronunciation: 'a-HOM',         english: 'to eat',                 category: 'action',  note: '', },
      { native: 'ⲥⲱⲧⲙ',        pronunciation: 'SOHTM',         english: 'to hear / to listen',    category: 'action',  note: 'Listening was the primary religious act — Coptic scripture was heard, not primarily read. The ear was the organ of faith.', },
      { native: 'ⲙⲉ',          pronunciation: 'meh',           english: 'truth / love',           category: 'emotion', note: 'In Coptic, truth and love were expressed by the same root. An untranslatable convergence — perhaps the most beautiful word on this page.', },
      { native: 'ⲟⲩⲱⲛϩ',       pronunciation: 'ou-WONH',       english: 'to reveal / to appear',  category: 'spirit',  note: 'God\'s action in the world was expressed as revelation — appearance from hiddenness. The word underpins all Coptic theology.', },
      { native: 'ⲡⲛⲉⲩⲙⲁ',      pronunciation: 'p-NYOO-ma',     english: 'spirit / breath',        category: 'spirit',  note: 'Borrowed from Greek — a sign of the early Christian church\'s influence on Coptic. The Greek word for spirit entered the language and stayed.', },
      { native: 'ⲑⲁⲗⲁⲥⲥⲁ',     pronunciation: 'tha-LAS-sa',    english: 'sea',                    category: 'nature',  note: 'Also borrowed from Greek — Egypt\'s relationship with the Mediterranean was Greek-mediated. The Nile had its own word; the sea was foreign.', },
      { native: 'ϩⲟⲟⲩ',        pronunciation: 'HOOU',          english: 'day',                    category: 'time',    note: '', },
      { native: 'ⲉϫⲟⲟⲩ',       pronunciation: 'e-JHOOU',       english: 'month',                  category: 'time',    note: 'The Coptic calendar — 13 months of 28-30 days each — is still used by the Ethiopian Orthodox church.', },
      { native: 'ⲣⲟⲙⲡⲉ',       pronunciation: 'ROHM-peh',      english: 'year',                   category: 'time',    note: 'The year was anchored to the Nile flood — a year was the cycle between inundations.', },
      { native: 'ⲉⲓⲱⲧ',        pronunciation: 'i-OHT',         english: 'father',                 category: 'kinship', note: 'The word for God the Father uses this root — divine and human fatherhood shared one word.', },
      { native: 'ⲙⲁⲁⲩ',        pronunciation: 'MAA-oo',        english: 'mother',                 category: 'kinship', note: 'Mary, the mother of Jesus, is addressed with this word in Coptic liturgy — sung in churches today.', },
      { native: 'ϣⲏⲣⲉ',        pronunciation: 'SHEE-reh',      english: 'child / son',            category: 'kinship', note: '', },
      { native: 'ⲛⲁⲓ',         pronunciation: 'nay',           english: 'mercy / have mercy',     category: 'emotion', note: 'The most common word in Coptic liturgy — Kyrie eleison in Greek, "nai nan" in Coptic. Every service contains it hundreds of times.', },
      { native: 'ⲟⲩⲱϣⲃ',       pronunciation: 'ou-OHSHB',      english: 'to answer / to respond', category: 'action',  note: 'Religious dialogue required answering — call and response structured all Coptic worship.', },
      { native: 'ϩⲏⲧ',         pronunciation: 'HEET',          english: 'heart / mind',           category: 'body',    note: 'Heart was the seat of thought in Coptic, as in ancient Egyptian. The mind lived in the chest, not the head.', },
      { native: 'ϭⲓϫ',         pronunciation: 'JI-j',          english: 'hand',                   category: 'body',    note: 'The hand of God was a theological concept — power expressed through touch and action.', },
      { native: 'ⲃⲁⲗ',         pronunciation: 'bal',           english: 'eye',                    category: 'body',    note: '', },
      { native: 'ⲣⲟ',          pronunciation: 'ro',            english: 'mouth / door',           category: 'body',    note: 'Mouth and door were the same word — the opening through which things passed. A word of thresholds.', },
      { native: 'ⲁⲛⲟⲕ',        pronunciation: 'a-NOK',         english: 'I / me',                 category: 'other',   note: 'The first-person pronoun descended from ancient Egyptian "ink" — three thousand years of selfhood, unchanged.', },
      { native: 'ⲛⲧⲟⲕ',        pronunciation: 'n-TOK',         english: 'you (masculine)',        category: 'other',   note: '', },
      { native: 'ⲥⲱⲡⲉ',        pronunciation: 'SOH-peh',       english: 'to become / to happen',  category: 'action',  note: 'Becoming was the primary verb of creation in Coptic theology — God spoke, and things became.', },
      { native: 'ⲙⲛⲧⲣⲙⲛ̄ϩⲏⲧ', pronunciation: 'mnt-rem-n-HEET', english: 'patience / long-suffering', category: 'emotion', note: 'Literally "longness of heart." Patience was not passive — it was an active stretching of the inner self.', },
      { native: 'ⲁⲅⲁⲡⲏ',       pronunciation: 'a-GA-pee',      english: 'divine love',            category: 'emotion', note: 'Borrowed from Greek — the specific love of God for humanity. Coptic absorbed the Greek theological vocabulary entirely.', },
    ]
  },
};
